# Generated by Django 3.2.4 on 2021-06-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('numberOfQuestions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Duration of quiz in minutes.')),
                ('requiredScoredToPass', models.IntegerField(help_text='Required score to pass in %')),
                ('difficulty', models.IntegerField(choices=[(1, 'easy'), (2, 'intermediate'), (3, 'difficult')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
    ]
