# Generated by Django 3.2.4 on 2021-06-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='numberOfQuestions',
            new_name='number_Of_Questions',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='requiredScoredToPass',
            new_name='required_Score_To_Pass',
        ),
    ]
