# Generated by Django 3.2.4 on 2021-06-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Difficult', 'Difficult')], max_length=12),
        ),
    ]
